// <auto-generated />
namespace Booker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class populataData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populataData));
        
        string IMigrationMetadata.Id
        {
            get { return "202405011416272_populataData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
